version: '3.9'
services:
  api-aidil-lorentech-population:
    image: aidil-lorentech-population/api
    container_name: api-aidil-lorentech-population
    build: .
    restart: always
    ports:
      - 6758:3000
    networks:
      connectors:
        ipv4_address: 183.77.86.100
    environment:
      - BASE_ENV_SRC=PRODUCTION
    depends_on:
      - db-aidil-lorentech-population
  db-aidil-lorentech-population:
    image: postgres:13.18-alpine
    container_name: db-aidil-lorentech-population
    ports:
      - "5498:5432"
    environment:
      POSTGRES_USER: aidil
      POSTGRES_PASSWORD: loren2025
    restart: always
    networks:
      connectors:
        ipv4_address: 183.77.86.5
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
networks:
  connectors:
    name: lorentech-aidil-network
    driver: bridge
    ipam:
      config:
        - subnet: "183.77.86.0/24"
          gateway: "183.77.86.1"
    attachable: true